on: [push]

jobs:
  buck2_default_job:
    runs-on: ubuntu-latest
    name: A job to try our buck2 composite action
    steps:
      - uses: actions/checkout@v4
      - name: Use buck2 composite action
        uses: zadlg/buck2-github-composite-action@v1
      - name: Verify that buck2 binary is available
        run: |
          /usr/bin/buck2 --version
